### ISSUE TITLE
Machine Request - AdoptOpenJDK

### ISSUE THREAD

**Issue by gdams** [theopenlab/ocean#3]
If you are interested in access to OpenLab resources, please fill out the details below. You can always find more information about OpenLab at https://openlabtesting.org

If you are just filing an issue, ignore/delete these fields and file your issue.

### Name
George Adams

### Email
george.adams@uk.ibm.com

### Company/Organization
AdoptOpenJDK/IBM

### Job Title
Developer Lead at AdoptOpenJDK + Node.js Developer at IBM

### What is your focus?
- [ ] Performance
- [ ] Scale
- [ ] Reliability
- [ ] Resiliency
- [ ] Integration
- [ ] Multi-Cloud
- [ ] Operational Tooling
- [ ] Edge or IoT
- [ ] Machine Learning
- [ ] Artificial Intelligence
- [ ] Application Ecosystem
- [x] Other

### If this is for an open source project what is it?
AdoptOpenJDK

### Brief project description
AdoptOpenJDK - adoptopenjdk is a project that builds, tests, and distributes Java runtime binaries that are based upon the open source [OpenJDK project](http://openjdk.java.net/).

The project has an established Jenkins continuous integration farm that provides software builds across a number of CPU/OS combinations, and testing of function and application-level correctness. The project distributes the resulting binaries via its website that is a portal for high-quality OpenJDK binaries.

### Is project code 100% open source? If so, what is the URL or URLs where it is located?
Yes, the delivered code, tests and build systems themselves are open source at https://github.com/AdoptOpenJDK. There is a minor exception, as we are obliged to run some proprietary code licensed directly from Oracle to pass the language compatibility test suites.
### What kind of machines (VMs or Baremetal) and how many do you expect to use?
VMs is fine but ideally ~32 macines in total 

### What OS are you planning to use?
Operating systems including UB16, UB18, RHEL, Fedora, Centos7, SLES12, OpenSUSE

### Any special network configuration you expect or anticipate implementing?
All machines need to public IP addresses or a way to ssh via jumpbox.

### Any architecture or other specifications/requirements (CPU, RAM, GPU, etc)?
Ideally 4cpu 8gb ram 120gb disk

### Please state your contributions to the open source community and any other relevant initiatives.
Developer Lead at [AdoptOpenJDK](https://github.com/AdoptOpenJDK/)
Core Collaborator at [Node.js Foundation](https://github.com/Nodejs/)
Developer at [CloudNativeJS](https://github.com/CloudNativeJS/)

### What testing are you planning to implement or need assistance implementing?
We have a variety of test suites that we are already running on all of our OpenJDK builds see [here](https://github.com/AdoptOpenJDK/openjdk-tests) for more information.

### How will this testing advance application and/or tooling built on-top of open infrastructure?
It will allow us to ensure that our OpenJDK binaries are of a good quality and work on all major distributions.

### Will you publish blog or paper from your testing?

- [x] Yes
- [ ] No - if no, how will you present your results?

### Any other relevant details we should know about while preparing the infrastructure?
ARM is an important platform for Java users, representing a significant community of application end-users. It remains important for Java to continue working on ARM, and by utilizing the AdoptOpenJDK infrastructure the project is able to provide prompt feedback to the language developers about the impact to ARM support and performance.

**Comment by gdams** [comment]
@mrhillsman any progress with this?

**Comment by mrhillsman** [comment]
@gdams yes, apologies as I thought I sent you this via email, please setup time to discuss at https://calendly.com/openlab

**Comment by kiwik** [comment]
We will use https://github.com/theopenlab/openlab/issues/119 to trace the task
